### ISSUE TITLE
Use "Referer" to replace "ID" in the tab

### ISSUE THREAD

**Issue by Giftedboy** [phlmox/BurpJSLinkFinderv2#2]
Sometime it's difficult to figure out  which site the "Path" belongs to though the js files cause the js files' domain is not the same to the original site.But "referer" helps.
![image](https://github.com/phlmox/BurpJSLinkFinderv2/assets/25588005/80e029ba-75ab-4b07-8779-e896aef03ea9)

**Comment by Giftedboy** [comment]
headers = self.helpers.analyzeRequest(ihrr.getHttpService(),ihrr.getRequest()).getHeaders()
referer = ""
for h in headers:
    if h.startswith("Referer"):
        referer = h.split("Referer:")[1].strip()
        break
if referer == "":
    referer = str(urlReq)

self.outputList.getModel().addRow([referer,str(urlReq),issueText['link']])

**Comment by phlmox** [comment]
Hi,

Thanks for your feedback I'll take a look at it soon
